V4A_PATH := packages/apps/ViPER4AndroidFX

PRODUCT_SOONG_NAMESPACES += $(V4A_PATH)

PRODUCT_PACKAGES += \
    ViPER4AndroidFX

SYSTEM_EXT_PRIVATE_SEPOLICY_DIRS += $(V4A_PATH)/sepolicy/private
BOARD_VENDOR_SEPOLICY_DIRS += $(V4A_PATH)/sepolicy/vendor
SYSTEM_EXT_PUBLIC_SEPOLICY_DIRS += $(V4A_PATH)/sepolicy/public
